global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    cluster: demo
    namespace: demo

scrape_configs:
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
        - 192.168.0.135:8081
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets:
        - 192.168.0.135:9091

