global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:

  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets:
        - 172.18.0.1:9091
  - job_name: node
    scrape_interval: 5s
    static_configs:
      - targets:
        - 172.18.0.1:9100
